### ISSUE TITLE
Can't open inspector and NullReferenceException when change lilToonLite

### ISSUE THREAD

**Issue by Kieaer** [lilxyzw/lilToon#65]
```
NullReferenceException: Object reference not set to an instance of an object
UnityEditor.MaterialEditor.GetPropertyRect (UnityEditor.MaterialProperty prop, System.String label, System.Boolean ignoreDrawer) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.MaterialEditor.GetPropertyRect (UnityEditor.MaterialProperty prop, UnityEngine.GUIContent label, System.Boolean ignoreDrawer) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.MaterialEditor.ShaderProperty (UnityEditor.MaterialProperty prop, UnityEngine.GUIContent label, System.Int32 labelIndent) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.MaterialEditor.ShaderProperty (UnityEditor.MaterialProperty prop, UnityEngine.GUIContent label) (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.MaterialEditor.ShaderProperty (UnityEditor.MaterialProperty prop, System.String label) (at <a259d3c004024353a2c217da97495055>:0)
lilToon.lilToonInspector.DrawBaseSettings (UnityEngine.Material material, System.String sCullModes, System.String sTransparentMode, System.String[] sRenderingModeList, System.String[] sRenderingModeListLite, System.String[] sTransparentModeList) (at Assets/Shaders/lilToon/Editor/lilInspector.cs:4229)
lilToon.lilToonInspector.DrawAdvancedGUI (UnityEngine.Material material) (at Assets/Shaders/lilToon/Editor/lilInspector.cs:1734)
lilToon.lilToonInspector.DrawAllGUI (UnityEditor.MaterialEditor materialEditor, UnityEditor.MaterialProperty[] props, UnityEngine.Material material) (at Assets/Shaders/lilToon/Editor/lilInspector.cs:1483)
lilToon.lilToonInspector.OnGUI (UnityEditor.MaterialEditor materialEditor, UnityEditor.MaterialProperty[] props) (at Assets/Shaders/lilToon/Editor/lilInspector.cs:1432)
UnityEditor.MaterialEditor.PropertiesGUI () (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.MaterialEditor.OnInspectorGUI () (at <a259d3c004024353a2c217da97495055>:0)
UnityEditor.UIElements.InspectorElement+<>c__DisplayClass58_0.<CreateIMGUIInspectorFromEditor>b__0 () (at <a259d3c004024353a2c217da97495055>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

```

Material values
```
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!21 &2100000
Material:
  serializedVersion: 6
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_Name: Dress_Sunao_2_lite
  m_Shader: {fileID: 4800000, guid: 381af8ba8e1740a41b9768ccfb0416c2, type: 3}
  m_ShaderKeywords: 
  m_LightmapFlags: 4
  m_EnableInstancingVariants: 0
  m_DoubleSidedGI: 0
  m_CustomRenderQueue: -1
  stringTagMap: {}
  disabledShaderPasses: []
  m_SavedProperties:
    serializedVersion: 3
    m_TexEnvs:
    - _BaseColorMap:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _BaseMap:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _EmissionMap:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _MainTex:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _MatCapTex:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _OutlineTex:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _OutlineWidthMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _Shadow2ndColorTex:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _ShadowColorTex:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    - _TriMask:
        m_Texture: {fileID: 0}
        m_Scale: {x: 1, y: 1}
        m_Offset: {x: 0, y: 0}
    m_Floats:
    - _AAStrength: 1
    - _AlphaBoostFA: 10
    - _AlphaToMask: 0
    - _AsUnlit: 0
    - _BackfaceForceShadow: 0
    - _BeforeExposureLimit: 10000
    - _BlendOp: 0
    - _BlendOpAlpha: 0
    - _BlendOpAlphaFA: 4
    - _BlendOpFA: 4
    - _ColorMask: 15
    - _Cull: 2
    - _Cutoff: 0.5
    - _DstBlend: 0
    - _DstBlendAlpha: 10
    - _DstBlendAlphaFA: 1
    - _DstBlendFA: 1
    - _EmissionMap_UVMode: 0
    - _FlipNormal: 0
    - _Invisible: 0
    - _LightMaxLimit: 1
    - _LightMinLimit: 0.05
    - _MatCapMul: 0
    - _MatCapPerspective: 1
    - _MatCapVRParallaxStrength: 1
    - _MatCapZRotCancel: 1
    - _MonochromeLighting: 0
    - _OffsetFactor: 0
    - _OffsetUnits: 0
    - _OutlineAlphaToMask: 0
    - _OutlineBlendOp: 0
    - _OutlineBlendOpAlpha: 0
    - _OutlineBlendOpAlphaFA: 4
    - _OutlineBlendOpFA: 4
    - _OutlineColorMask: 15
    - _OutlineCull: 1
    - _OutlineDeleteMesh: 0
    - _OutlineDstBlend: 0
    - _OutlineDstBlendAlpha: 10
    - _OutlineDstBlendAlphaFA: 1
    - _OutlineDstBlendFA: 1
    - _OutlineEnableLighting: 1
    - _OutlineFixWidth: 1
    - _OutlineOffsetFactor: 0
    - _OutlineOffsetUnits: 0
    - _OutlineSrcBlend: 1
    - _OutlineSrcBlendAlpha: 1
    - _OutlineSrcBlendAlphaFA: 0
    - _OutlineSrcBlendFA: 1
    - _OutlineStencilComp: 8
    - _OutlineStencilFail: 0
    - _OutlineStencilPass: 0
    - _OutlineStencilReadMask: 255
    - _OutlineStencilRef: 0
    - _OutlineStencilWriteMask: 255
    - _OutlineStencilZFail: 0
    - _OutlineVertexR2Width: 0
    - _OutlineWidth: 0.05
    - _OutlineZBias: 0
    - _OutlineZClip: 1
    - _OutlineZTest: 2
    - _OutlineZWrite: 1
    - _RimBlur: 0.1
    - _RimBorder: 0.5
    - _RimFresnelPower: 3
    - _RimShadowMask: 0
    - _Shadow2ndBlur: 0.3
    - _Shadow2ndBorder: 0.5
    - _ShadowBlur: 0.1
    - _ShadowBorder: 0.5
    - _ShadowBorderRange: 0
    - _ShadowEnvStrength: 0
    - _ShiftBackfaceUV: 0
    - _SrcBlend: 1
    - _SrcBlendAlpha: 1
    - _SrcBlendAlphaFA: 0
    - _SrcBlendFA: 1
    - _StencilComp: 8
    - _StencilFail: 0
    - _StencilPass: 0
    - _StencilReadMask: 255
    - _StencilRef: 0
    - _StencilWriteMask: 255
    - _StencilZFail: 0
    - _SubpassCutoff: 0.5
    - _UseEmission: 0
    - _UseMatCap: 0
    - _UseRim: 0
    - _UseShadow: 0
    - _VertexLightStrength: 0
    - _ZClip: 1
    - _ZTest: 4
    - _ZWrite: 1
    - _lilDirectionalLightStrength: 1
    - _lilShadowCasterBias: 0
    - _lilToonVersion: 33
    m_Colors:
    - _BaseColor: {r: 1, g: 1, b: 1, a: 1}
    - _Color: {r: 1, g: 1, b: 1, a: 1}
    - _EmissionBlink: {r: 0, g: 0, b: 3.141593, a: 0}
    - _EmissionColor: {r: 1, g: 1, b: 1, a: 1}
    - _EmissionMap_ScrollRotate: {r: 0, g: 0, b: 0, a: 0}
    - _LightDirectionOverride: {r: 0.001, g: 0.002, b: 0.001, a: 0}
    - _MainTex_ScrollRotate: {r: 0, g: 0, b: 0, a: 0}
    - _MatCapBlendUV1: {r: 0, g: 0, b: 0, a: 0}
    - _OutlineColor: {r: 0.8, g: 0.85, b: 0.9, a: 1}
    - _OutlineTex_ScrollRotate: {r: 0, g: 0, b: 0, a: 0}
    - _RimColor: {r: 1, g: 1, b: 1, a: 1}
    - _ShadowBorderColor: {r: 1, g: 0, b: 0, a: 1}
```
